name       : python-pandocfilters
version    : 1.5.0
release    : 7
source     :
    - https://github.com/jgm/pandocfilters/archive/refs/tags/1.5.0.tar.gz : c31a00bd7b1d6c25eeb84e0db6b5e6d75f266e85b3eecdc91f048736147f07bc
homepage   : https://github.com/jgm/pandocfilters
license    : BSD-3-Clause
component  : programming.python
summary    : Utilities for writing pandoc filters in python
description: |
    Pandoc filters are pipes that read a JSON serialization of the Pandoc AST from stdin, transform it in some way, and write it to stdout.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
