name       : python-pandocfilters
version    : 1.4.2
release    : 2
source     :
    - https://github.com/jgm/pandocfilters/archive/1.4.2.tar.gz : bdb230dfbef7e4a6222620898b148b2678b2324f822a301c84ae87d788d141ed
license    : BSD-3-Clause
component  : programming.python
summary    : A python module for writing pandoc filters, with a collection of examples.
description: |
    A python module for writing pandoc filters, with a collection of examples.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
